# Generated by Django 5.1.15 on 2026-08-03 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trips", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "token",
                    models.SlugField(max_length=64, unique=True, verbose_name="token"),
                ),
                ("qr_code_url", models.URLField(blank=True, verbose_name="QR Code")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expira em"
                    ),
                ),
                (
                    "trip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("name", models.CharField(max_length=140, verbose_name="nome")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="telefone"
                    ),
                ),
                (
                    "document",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="documento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Inscrito"),
                            ("confirmed", "Confirmado"),
                            ("cancelled", "Cancelado"),
                            ("waitlisted", "Lista de espera"),
                        ],
                        default="registered",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True, max_length=140, verbose_name="contato de emergência"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="observações")),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="trips.trip",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
