# Generated by Django 5.1.15 on 2026-08-18 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0001_initial"),
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="data de nascimento"
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="boarding_point",
            field=models.CharField(
                blank=True, max_length=140, verbose_name="ponto de embarque"
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="consent_accepted",
            field=models.BooleanField(default=False, verbose_name="aceitou os termos"),
        ),
        migrations.AddField(
            model_name="participant",
            name="consent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="aceite em"),
        ),
        migrations.AddField(
            model_name="participant",
            name="dietary_restrictions",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="restrição alimentar"
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="guardian_document",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="documento do responsável"
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="guardian_name",
            field=models.CharField(
                blank=True, max_length=140, verbose_name="responsável"
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="guardian_phone",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="telefone do responsável"
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="health_insurance",
            field=models.CharField(
                blank=True, max_length=140, verbose_name="plano de saúde"
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="is_minor",
            field=models.BooleanField(default=False, verbose_name="menor de idade"),
        ),
        migrations.AddField(
            model_name="participant",
            name="medical_notes",
            field=models.TextField(
                blank=True, verbose_name="observações médicas / medicamentos"
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="room_group",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="quarto / grupo"
            ),
        ),
        migrations.AddField(
            model_name="participant",
            name="shirt_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PP", "PP"),
                    ("P", "P"),
                    ("M", "M"),
                    ("G", "G"),
                    ("GG", "GG"),
                    ("XGG", "XGG"),
                ],
                max_length=4,
                verbose_name="tamanho de camiseta",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="document",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="documento (CPF/RG)"
            ),
        ),
        migrations.CreateModel(
            name="TripRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("name", models.CharField(max_length=140, verbose_name="item")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="descrição"
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[("all", "Todos"), ("minors", "Somente menores")],
                        default="all",
                        max_length=10,
                        verbose_name="aplica-se a",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=True, verbose_name="obrigatório"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ordem")),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ParticipantRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "delivered",
                    models.BooleanField(default=False, verbose_name="entregue"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="entregue em"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="observação"
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirement_status",
                        to="participants.participant",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_status",
                        to="participants.triprequirement",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="triprequirement",
            constraint=models.UniqueConstraint(
                fields=("trip", "name"), name="unique_requirement_per_trip"
            ),
        ),
        migrations.AddConstraint(
            model_name="participantrequirement",
            constraint=models.UniqueConstraint(
                fields=("participant", "requirement"),
                name="unique_participant_requirement",
            ),
        ),
    ]
