# Generated by Django 5.1.15 on 2026-08-03 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("name", models.CharField(max_length=140, verbose_name="nome")),
                (
                    "destination",
                    models.CharField(max_length=200, verbose_name="destino"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("church", "Igreja"),
                            ("school", "Escola"),
                            ("family", "Família"),
                            ("friends", "Amigos"),
                            ("corporate", "Corporativa"),
                            ("event", "Evento"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="início"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="fim"),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="duração (dias)"
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="limite de vagas"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=160, unique=True, verbose_name="slug"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("published", "Publicada"),
                            ("closed", "Encerrada"),
                            ("archived", "Arquivada"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "cover_image_url",
                    models.URLField(blank=True, verbose_name="imagem de capa"),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="título")),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                ("done", models.BooleanField(default=False, verbose_name="concluída")),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="prazo"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("ai", "IA"), ("manual", "Manual")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["done", "due_date"],
            },
        ),
        migrations.CreateModel(
            name="BudgetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("transport", "Transporte"),
                            ("lodging", "Hospedagem"),
                            ("meals", "Alimentação"),
                            ("tickets", "Ingressos"),
                            ("extra", "Extras"),
                        ],
                        max_length=20,
                        verbose_name="categoria",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="descrição"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="valor"
                    ),
                ),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixo (rateado)"),
                            ("per_person", "Por pessoa"),
                        ],
                        default="fixed",
                        max_length=20,
                        verbose_name="tipo de custo",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_items",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TripConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "has_lodging",
                    models.BooleanField(default=False, verbose_name="tem hospedagem"),
                ),
                (
                    "has_meals",
                    models.BooleanField(default=False, verbose_name="tem alimentação"),
                ),
                (
                    "has_chartered_transport",
                    models.BooleanField(
                        default=False, verbose_name="transporte fretado"
                    ),
                ),
                (
                    "has_rooms",
                    models.BooleanField(default=False, verbose_name="tem quartos"),
                ),
                (
                    "has_groups",
                    models.BooleanField(default=False, verbose_name="tem grupos"),
                ),
                (
                    "has_capacity_limit",
                    models.BooleanField(
                        default=False, verbose_name="tem limite de vagas"
                    ),
                ),
                (
                    "safety_margin_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="margem de segurança (%)",
                    ),
                ),
                (
                    "trip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
