# Generated by Django 5.1.15 on 2026-08-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pix_bank",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="instituição"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pix_key_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cpf", "CPF"),
                    ("cnpj", "CNPJ"),
                    ("email", "E-mail"),
                    ("phone", "Telefone"),
                    ("random", "Chave aleatória"),
                ],
                max_length=10,
                verbose_name="tipo da chave",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pix_owner_name",
            field=models.CharField(
                blank=True, max_length=140, verbose_name="nome do favorecido"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pix_payload",
            field=models.TextField(blank=True, verbose_name="PIX copia e cola"),
        ),
        migrations.AddField(
            model_name="user",
            name="pix_qr_image",
            field=models.TextField(blank=True, verbose_name="imagem do QR Code"),
        ),
    ]
